# User-level install of the vendored OpenSpec Claude assets:
#   - the superpowers-bridge schema bundle, delivered user-global
#   - the global openspec config.json pinned to the 11-workflow custom profile
#   - the OpenSpec CLI itself (programs.openspec.package)
#
# The 11 generated openspec-* skills are NOT delivered by this module. They live
# in the planning-and-development apm package
# (modules/home/ai/plugins/planning-and-development/.apm/skills/) and ship through
# apm-skills-compose alongside the other first-party skills, so this module no
# longer contributes an aiSkills.extraSkillDirs entry.
#
# Opt-in member of the homeManager.ai aggregate: the config applies only to
# users who set programs.openspec.enable = true (e.g. crs58). The schema bundle is
# committed generated output; it and the in-package skills are regenerated via the
# openspec-refresh-vendored-artifacts flake app (nix run .#openspec-refresh-vendored-artifacts).
{ ... }:
{
  flake.modules.homeManager.ai =
    {
      config,
      pkgs,
      lib,
      flake,
      ...
    }:
    let
      cfg = config.programs.openspec;
      assetsDir = flake.inputs.self + "/modules/home/ai/openspec/assets";
      jsonFormat = pkgs.formats.json { };
    in
    {
      options.programs.openspec = {
        enable = lib.mkEnableOption "the vendored OpenSpec user-level Claude assets (CLI, skills, schema bundle, and global config.json)";

        package = lib.mkOption {
          type = lib.types.nullOr lib.types.package;
          default = flake.inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system}.openspec;
          defaultText = lib.literalExpression "inputs.llm-agents.packages.\${pkgs.stdenv.hostPlatform.system}.openspec";
          description = ''
            The OpenSpec CLI package to install, or null to install none (e.g. when
            another aggregate provides it). Sourced from the llm-agents input, which
            is not in nixpkgs, so this is a plain package option rather than
            {function}`lib.mkPackageOption`.
          '';
        };

        profile = lib.mkOption {
          type = lib.types.enum [
            "core"
            "custom"
          ];
          default = "custom";
          example = "custom";
          description = ''
            OpenSpec global profile written to {file}`config.json`. `custom`
            activates the explicit {option}`programs.openspec.workflows` list;
            `core` uses OpenSpec's built-in core set.
          '';
        };

        delivery = lib.mkOption {
          type = lib.types.enum [
            "both"
            "skills"
            "commands"
          ];
          default = "skills";
          example = "both";
          description = ''
            How OpenSpec delivers workflow artifacts: as Claude skills, as slash
            commands, or both. Defaults to `skills`: the `/opsx:*` slash commands
            are 1:1 duplicates of the `openspec-*` skills, and the non-Claude
            harnesses (codex, opencode, droid, hermes) consume skills, not
            commands, so the command tree is redundant.
          '';
        };

        workflows = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [
            "propose"
            "explore"
            "new"
            "continue"
            "apply"
            "ff"
            "sync"
            "archive"
            "bulk-archive"
            "verify"
            "onboard"
          ];
          defaultText = lib.literalExpression ''[ "propose" "explore" "new" "continue" "apply" "ff" "sync" "archive" "bulk-archive" "verify" "onboard" ]'';
          example = lib.literalExpression ''[ "propose" "apply" "archive" ]'';
          description = ''
            Workflow ids baked into the custom profile. Must stay in sync with the
            vendored assets, which are regenerated by
            `nix run .#openspec-refresh-vendored-artifacts` (the regen sidecar's
            sandbox config.json carries the same list).
          '';
        };

        schemaDir = lib.mkOption {
          type = lib.types.nullOr lib.types.path;
          default = assetsDir + "/schemas/superpowers-bridge";
          defaultText = lib.literalExpression ''inputs.self + "/modules/home/ai/openspec/assets/schemas/superpowers-bridge"'';
          description = ''
            Schema bundle materialized (recursively, via lndir) under
            {file}`~/.local/share/openspec/schemas/superpowers-bridge` so that
            `openspec new --schema superpowers-bridge` resolves. `recursive = true`
            is required: OpenSpec's discovery skips symlinked directories. Set to
            null to deliver no schema bundle.
          '';
        };

        settings = lib.mkOption {
          inherit (jsonFormat) type;
          default = {
            featureFlags = { };
            profile = cfg.profile;
            delivery = cfg.delivery;
            workflows = cfg.workflows;
            telemetry = {
              noticeSeen = true;
              anonymousId = "00000000-0000-0000-0000-000000000000";
            };
          };
          defaultText = lib.literalExpression ''
            {
              featureFlags = { };
              profile = config.programs.openspec.profile;
              delivery = config.programs.openspec.delivery;
              workflows = config.programs.openspec.workflows;
              telemetry = {
                noticeSeen = true;
                anonymousId = "00000000-0000-0000-0000-000000000000";
              };
            }'';
          example = lib.literalExpression "{ featureFlags.experimental = true; }";
          description = ''
            Freeform contents of OpenSpec's global
            {file}`$XDG_CONFIG_HOME/openspec/config.json`, validated upstream by a
            passthrough zod schema. Defaults are derived from
            {option}`programs.openspec.profile`, {option}`programs.openspec.delivery`,
            and {option}`programs.openspec.workflows`; override or extend here for
            keys this module does not model.

            Delivered as a read-only symlink into the nix store. This is safe: the
            only writer on ordinary (read) commands is the telemetry preAction hook,
            which writes solely to add a missing telemetry.noticeSeen/anonymousId and
            only when telemetry is enabled; both writes are wrapped in try/catch, so a
            failed write on a read-only file is swallowed and the command still
            succeeds (verified with @fission-ai/openspec@1.4.1). Both telemetry fields
            are pre-set so no write is ever attempted.
          '';
        };
      };

      config = lib.mkIf cfg.enable {
        # The OpenSpec CLI. Owned here (not development-packages) now that a module
        # exists; null disables installing it.
        home.packages = lib.mkIf (cfg.package != null) [ cfg.package ];

        # Deliver the schema bundle user-global. recursive = true is REQUIRED:
        # OpenSpec's schema discovery skips directory SYMLINKS (listSchemas gates on
        # dirent.isDirectory(), false for a symlinked dir), so lndir materializes a
        # real dir with symlinked file leaves, which discovery enumerates fine. A
        # bare `.source` symlink is invisible ("Unknown schema"). See assets/schemas/README.md.
        home.file.".local/share/openspec/schemas/superpowers-bridge" = lib.mkIf (cfg.schemaDir != null) {
          source = cfg.schemaDir;
          recursive = true;
        };

        # Deliver the global config.json via the json format generator (RFC-42
        # settings), not builtins.toJSON, so it is overridable and extensible.
        xdg.configFile."openspec/config.json".source =
          jsonFormat.generate "openspec-config.json" cfg.settings;
      };
    };
}
