{ config, inputs, ... }:
{
  flake.modules.homeManager.ai.imports = [ config.flake.modules.homeManager.openspec ];
  flake.modules.homeManager.openspec =
    {
      config,
      pkgs,
      lib,
      flake,
      ...
    }:
    let
      cfg = config.programs.openspec;
      assetsDir = inputs.self + "/modules/home/ai/openspec/assets";
      jsonFormat = pkgs.formats.json { };
    in
    {
      key = "vanixiets/openspec-home-module";

      options.programs.openspec = {
        enable = lib.mkEnableOption "the vendored OpenSpec user-level Claude assets (CLI, skills, schema bundle, and global config.json)";

        package = lib.mkOption {
          type = lib.types.nullOr lib.types.package;
          default = flake.inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system}.openspec;
          defaultText = lib.literalExpression "inputs.llm-agents.packages.\${pkgs.stdenv.hostPlatform.system}.openspec";
          description = ''
            The OpenSpec CLI package to install, or null to install none (e.g. when
            another aggregate provides it). Sourced from the llm-agents input, which
            is not in nixpkgs, so this is a plain package option rather than
            {function}`lib.mkPackageOption`.
          '';
        };

        profile = lib.mkOption {
          type = lib.types.enum [
            "core"
            "custom"
          ];
          default = "custom";
          example = "custom";
          description = ''
            OpenSpec global profile written to {file}`config.json`. `custom`
            activates the explicit {option}`programs.openspec.workflows` list;
            `core` uses OpenSpec's built-in core set.
          '';
        };

        delivery = lib.mkOption {
          type = lib.types.enum [
            "both"
            "skills"
            "commands"
          ];
          default = "skills";
          example = "both";
          description = ''
            How OpenSpec delivers workflow artifacts: as Claude skills, as slash
            commands, or both. Defaults to `skills`: the `/opsx:*` slash commands
            are 1:1 duplicates of the `openspec-*` skills, and the non-Claude
            harnesses (codex, opencode, droid, hermes) consume skills, not
            commands, so the command tree is redundant.
          '';
        };

        workflows = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [
            "propose"
            "explore"
            "new"
            "continue"
            "apply"
            "update"
            "ff"
            "sync"
            "archive"
            "bulk-archive"
            "verify"
            "onboard"
          ];
          defaultText = lib.literalExpression ''[ "propose" "explore" "new" "continue" "apply" "update" "ff" "sync" "archive" "bulk-archive" "verify" "onboard" ]'';
          example = lib.literalExpression ''[ "propose" "apply" "archive" ]'';
          description = ''
            Workflow ids baked into the custom profile. Must stay in sync with the
            vendored assets, which are regenerated by
            `nix run .#openspec-refresh-vendored-artifacts` (the regen sidecar's
            sandbox config.json carries the same list).
          '';
        };

        schemaDirs = lib.mkOption {
          type = lib.types.attrsOf lib.types.path;
          default = lib.genAttrs [ "superpowers-bridge" "superpowers-bridge-wrspm" ] (
            name: assetsDir + "/schemas/${name}"
          );
          defaultText = lib.literalExpression ''
            lib.genAttrs [ "superpowers-bridge" "superpowers-bridge-wrspm" ] (
              name: inputs.self + "/modules/home/ai/openspec/assets/schemas/''${name}"
            )
          '';
          description = ''
            Schema bundles delivered as directory symlinks at
            {file}`~/.local/share/openspec/schemas/<name>`, keyed by the name the
            OpenSpec CLI resolves, so `openspec new --schema <name>` and any change
            pinned to `<name>` both resolve.

            Both bundles are delivered deliberately. A change records its schema in
            its own {file}`.openspec.yaml` at creation time and is never repinned,
            so withdrawing a bundle strands every change already pinned to it with
            an unresolvable schema and no diagnostic beyond the `schema=` attribute
            of `openspec instructions` output.

            Set to `{ }` to deliver no schema bundle.
          '';
        };

        settings = lib.mkOption {
          inherit (jsonFormat) type;
          default = {
            featureFlags = { };
            profile = cfg.profile;
            delivery = cfg.delivery;
            workflows = cfg.workflows;
            telemetry = {
              noticeSeen = true;
              anonymousId = "00000000-0000-0000-0000-000000000000";
            };
          };
          defaultText = lib.literalExpression ''
            {
              featureFlags = { };
              profile = config.programs.openspec.profile;
              delivery = config.programs.openspec.delivery;
              workflows = config.programs.openspec.workflows;
              telemetry = {
                noticeSeen = true;
                anonymousId = "00000000-0000-0000-0000-000000000000";
              };
            }'';
          example = lib.literalExpression "{ featureFlags.experimental = true; }";
          description = ''
            Freeform contents of OpenSpec's global
            {file}`$XDG_CONFIG_HOME/openspec/config.json`, validated upstream by a
            passthrough zod schema. Defaults are derived from
            {option}`programs.openspec.profile`, {option}`programs.openspec.delivery`,
            and {option}`programs.openspec.workflows`; override or extend here for
            keys this module does not model.

            Delivered as a read-only symlink into the nix store. This is safe: the
            only writer on ordinary (read) commands is the telemetry preAction hook,
            which writes solely to add a missing telemetry.noticeSeen/anonymousId and
            only when telemetry is enabled; both writes are wrapped in try/catch, so a
            failed write on a read-only file is swallowed and the command still
            succeeds (verified with @fission-ai/openspec@1.4.1). Both telemetry fields
            are pre-set so no write is ever attempted.
          '';
        };
      };

      config = lib.mkIf cfg.enable {
        home.packages = lib.mkIf (cfg.package != null) [ cfg.package ];

        # OpenSpec canonicalizes <schema dir>/schema.yaml and rejects a result outside
        # the canonicalized schema directory (resolver.js getSchemaCandidateDir ->
        # FileSystemUtils.assertPathWithin), so per-file symlinks into the store are
        # unresolvable: `recursive = true` here breaks schema resolution.
        home.file = lib.mapAttrs' (
          name: src: lib.nameValuePair ".local/share/openspec/schemas/${name}" { source = src; }
        ) cfg.schemaDirs;

        xdg.configFile."openspec/config.json".source =
          jsonFormat.generate "openspec-config.json" cfg.settings;
      };
    };
}
