keys:
  # Repository-specific keys (working on vanixiets source)
  - &dev age1js028xag70wpwpp47elpq50mjjv7zn7sxuwuhk8yltkjzqzdvq5qq8w8cy      # from sops-dev-ssh in Bitwarden
  - &ci age1ldx73kk4kvl3mycjdhngxrrv69wn7cvhreqwzl0gphuftnj5pulqaprgel        # from sops-ci-ssh in Bitwarden

  # Admin recovery key (offline, not in Bitwarden)
  - &admin age1vy7wsnf8eg5229evq3ywup285jzk9cntsx5hhddjtwsjh0kf4c6s9fmalv

  # User identity keys (from config.nix)
  - &admin-user age1vn8fpkmkzkjttcuc3prq3jrp7t5fsrdqey74ydu5p88keqmcupvs8jtmv8  # from sops-admin-user-ssh (cameron/crs58/runner/jovyan)
  - &raquel-user age12w0rmmskrds6m334w7qrcmpms5lpe3llah6wf8ry5jtatvuxku2sarl8ut  # from sops-raquel-user-ssh (raquel)
  - &janettesmith-user age1mqfqckczkulpne7265j5cxn0pspdlxd3d0kav368u2c2fwknnc4qe27dec  # derived from SSH key via ssh-to-age
  - &christophersmith-user age1xz7gmqx7m0pn8u2nq8x05efq6dj52ym6c9gat5xj4am6x9sauq6sfzd2fn  # derived from SSH key via ssh-to-age

  # Host keys (generated in Bitwarden, deployed to /etc/ssh/)
  - &stibnite age1a696klqy0s36a2pzlk6kyckp60k88qxcrsdh829dtk3xtc7sfs4scg05k0     # from sops-stibnite-ssh
  - &blackphos age1ez8lkukzdjn8vqj8ly4k5y9eql5gz00mwyz3h2qhkh5m5tdzmc3swxkmdq   # from sops-blackphos-ssh
  - &orb-nixos age140evke8tz6a8k8h04rqfxvxvzkkz5wc9femda0xthwzlk227dpwqsl7zfc   # from sops-orb-nixos-ssh

creation_rules:
  # Per-user signing keys (minimal encryption - only that user + dev + admin)
  - path_regex: secrets/users/admin-user/signing-key\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user

  - path_regex: secrets/users/raquel-user/signing-key\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *raquel-user

  # Other admin-user secrets (llm-api-keys, mcp-api-keys, etc.)
  - path_regex: secrets/users/admin-user/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user

  # Other raquel-user secrets
  - path_regex: secrets/users/raquel-user/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *raquel-user

  # Home-manager user secrets (two-tier architecture from test-clan)
  - path_regex: secrets/home-manager/users/crs58/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user

  - path_regex: secrets/home-manager/users/raquel/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *raquel-user

  - path_regex: secrets/home-manager/users/janettesmith/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *janettesmith-user

  - path_regex: secrets/home-manager/users/christophersmith/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *christophersmith-user

  # Host-specific secrets
  - path_regex: secrets/hosts/stibnite/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user
        - *stibnite

  - path_regex: secrets/hosts/blackphos/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user
        - *blackphos

  - path_regex: secrets/hosts/orb-nixos/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user
        - *orb-nixos

  # Kubernetes cluster secrets (local dev cluster - admin access only)
  - path_regex: secrets/clusters/local/.*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user

  # Shared secrets (everyone can access)
  - path_regex: (secrets/services/.*\.yaml$|secrets/shared\.yaml$|secrets/test\.yaml$)
    key_groups:
      - age:
        - *admin
        - *dev
        - *ci
        - *admin-user
        - *raquel-user
        - *janettesmith-user
        - *christophersmith-user
        - *stibnite
        - *blackphos
        - *orb-nixos

  # Fallback
  - path_regex: .*\.yaml$
    key_groups:
      - age:
        - *admin
        - *dev
        - *admin-user
        - *stibnite
        - *blackphos
        - *orb-nixos
