{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  flakeModules = config.flake.modules.darwin;
  flakeUsers = config.flake.users;
  # sops-nix requires flake in extraSpecialArgs
  flakeForHomeManager = config.flake // {
    inherit inputs;
  };
in
{
  flake.modules.darwin."machines/darwin/argentum" =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    {
      _module.args.flake = inputs.self;

      imports = [
        inputs.home-manager.darwinModules.home-manager
        inputs.srvos.darwinModules.server
      ]
      ++ (with flakeModules; [
        base
        ssh-ca-trust
        ssh-known-hosts
        zt-dns
        # Not importing users module (defines testuser at UID 550)
        # argentum defines its own users (christophersmith + cameron)
      ]);

      # Re-enable documentation for laptop use
      # Override both srvos and clan-core defaults
      srvos.server.docs.enable = lib.mkForce true;
      documentation.enable = lib.mkForce true;
      documentation.doc.enable = lib.mkForce true;
      documentation.info.enable = lib.mkForce true;
      documentation.man.enable = lib.mkForce true;
      programs.info.enable = lib.mkForce true;
      programs.man.enable = lib.mkForce true;

      networking.hostName = "argentum";
      networking.computerName = "argentum";

      # Remote deployment target (enables `clan machines update` from stibnite)
      clan.core.networking.targetHost = "cameron@argentum.zt";

      nixpkgs.hostPlatform = "aarch64-darwin";

      # System state version (matching vanixiets configuration)
      # Override base.nix which sets stateVersion = 5
      system.stateVersion = lib.mkForce 4;

      # Match GID to fresh Nix installation (DeterminateSystems installer uses 350 since Aug 2024)
      # See: https://github.com/DeterminateSystems/nix-installer/pull/1123
      ids.gids.nixbld = 350;

      # Accept existing nix.conf from nix-installer
      # Hash generated by: shasum -a 256 /etc/nix/nix.conf
      # This allows nix-darwin to replace the file during first activation
      environment.etc."nix/nix.conf".knownSha256Hashes = [
        "5304bbb86b6b5d0a6ae04a7bab297c0fece1b159caf87bb5a757264ad2bddf0b"
      ];

      # Migrate trusted-users from /etc/nix/nix.custom.conf to nix-darwin
      # Required for accepting flake-specified substituters without prompts
      nix.settings.trusted-users = [
        "root"
        "@admin"
        "@wheel"
      ];

      # Primary user for homebrew and system-level user operations
      # cameron is the admin user on argentum (manages homebrew)
      system.primaryUser = "cameron";

      custom.profile.isDesktop = true;

      # Base casks from modules/darwin/homebrew.nix; machine-specific additions below
      custom.homebrew = {
        enable = true;

        # Simplified for basic user - only zerotier for network connectivity
        # Omitted developer casks: riptide-beta, dbeaver-community, docker-desktop,
        # gpg-suite, inkscape, keycastr, meld, postgres-app
        additionalCasks = [
          "zerotier-one"
        ];

        # Fonts managed via base homebrew module (manageFonts defaults to true)
      };

      security.pam.services.sudo_local.touchIdAuth = true;

      # Increase MaxAuthTries to accommodate agent forwarding with many keys
      # Default is 6, but Bitwarden SSH agent may have 10+ keys loaded
      # nix-darwin writes this to /etc/ssh/sshd_config.d/100-nix-darwin.conf
      services.openssh.extraConfig = ''
        MaxAuthTries 20
      '';

      # UIDs based on standard macOS assignment
      users.users.christophersmith = {
        uid = 501; # Primary user
        home = "/Users/christophersmith";
        shell = pkgs.zsh;
        description = "christophersmith";
        openssh.authorizedKeys.keys = inputs.self.users.christophersmith.meta.sshKeys;
      };

      users.users.cameron = {
        uid = 502; # Admin user
        home = "/Users/cameron";
        # shell and authorizedKeys provided by cameron inventory service
        description = "cameron";
      };

      # Darwin requires explicit knownUsers
      # Not managing root user (no users.users.root definition)
      users.knownUsers = [
        "christophersmith"
        "cameron"
      ];

      environment.systemPackages = with pkgs; [
        vim
        git
      ];

      programs.zsh.enable = true;

      home-manager = {
        useGlobalPkgs = true;
        useUserPackages = true;

        backupFileExtension = "before-home-manager";

        # Pass flake as extraSpecialArgs for sops-nix access
        extraSpecialArgs = {
          flake = flakeForHomeManager;
        };

        users.christophersmith.imports =
          flakeUsers.christophersmith.aggregates
          ++ [ flakeUsers.christophersmith.contentPrivate ]
          ++ [ flakeUsers.christophersmith.identity ];

        # cameron is an alias for crs58; alias-keyed reads keep this
        # call site ignorant of the alias->target relationship.
        users.cameron.imports =
          flakeUsers.cameron.aggregates
          ++ [ flakeUsers.cameron.contentPrivate ]
          ++ [ flakeUsers.cameron.identity ];
      };
    };
}
