# moshi-hook - companion daemon and CLI bridging local coding agents to the
# Moshi mobile app.
#
# Vendor-binary packaging rather than a source build: moshi-hook has no public
# source repository. The vendor publishes only prebuilt per-platform tarballs
# under https://cdn.getmoshi.app/hook/<version>/, and both documented install
# paths -- the rjyo/moshi Homebrew tap and https://getmoshi.app/install.sh --
# resolve to exactly those assets. The tap's formula is generated by the
# vendor's own release script and carries the same four URLs and SHA-256 sums
# reproduced here, so this derivation pins what Homebrew would have fetched and
# leaves no reason to route the daemon through Homebrew at all.
#
# The vendor's checksums.txt is the hash source; `update.sh` reads it rather
# than re-hashing downloads, which keeps the pinned digests provably equal to
# the ones the vendor published.
{
  lib,
  stdenv,
  fetchurl,
  versionCheckHook,
}:
let
  inherit (stdenv.hostPlatform) system;
  # Upstream names assets by `uname -s` and `uname -m` output rather than by
  # target triple: Darwin/Linux crossed with x86_64/arm64.
  systemToAsset = {
    "aarch64-darwin" = {
      label = "Darwin_arm64";
      hash = "sha256-tGTRaxIqzlyMNCiKcXmVtPdD45Yc+pJhtbqLYWPX5tw=";
    };
    "x86_64-darwin" = {
      label = "Darwin_x86_64";
      hash = "sha256-doZeWxB5ZqCs6pfg6b4ePbLAaTDNZAZnKoWYdWlBk2Q=";
    };
    "aarch64-linux" = {
      label = "Linux_arm64";
      hash = "sha256-0QVwP7BT5q9BbnucqdjOOx+0iEQ1haHF6kX9OSukgRg=";
    };
    "x86_64-linux" = {
      label = "Linux_x86_64";
      hash = "sha256-AkFhSriCghWYAMr5oKZSMLjpJ+IfAqbTTsws/tx4JVA=";
    };
  };
  asset = systemToAsset.${system} or (throw "moshi-hook: unsupported platform ${system}");
in
stdenv.mkDerivation (finalAttrs: {
  pname = "moshi-hook";
  version = "0.3.26";

  src = fetchurl {
    url = "https://cdn.getmoshi.app/hook/v${finalAttrs.version}/moshi-hook_${asset.label}.tar.gz";
    inherit (asset) hash;
  };

  # The tarball holds the executable, README.md, and docs/ at its root with no
  # containing directory.
  sourceRoot = ".";

  dontConfigure = true;
  dontBuild = true;

  # The Linux assets are statically linked Go, so there is nothing to patchelf.
  # The darwin assets carry a Developer ID signature with the hardened runtime
  # (TeamIdentifier FL442366Y7); stripping rewrites the Mach-O and invalidates
  # that signature, after which macOS refuses to exec the binary.
  dontStrip = stdenv.hostPlatform.isDarwin;

  installPhase = ''
    runHook preInstall

    install -Dm755 moshi-hook $out/bin/moshi-hook
    # The vendor's own Homebrew formula installs this alias, and the documented
    # `moshi <dir>` tmux launcher is reachable only under that name.
    ln -s moshi-hook $out/bin/moshi

    install -Dm644 README.md -t $out/share/doc/moshi-hook
    install -Dm644 docs/*.md -t $out/share/doc/moshi-hook

    runHook postInstall
  '';

  doInstallCheck = true;
  nativeInstallCheckInputs = [ versionCheckHook ];

  passthru.updateScript = ./update.sh;

  meta = {
    homepage = "https://getmoshi.app";
    description = "Daemon and CLI bridging local coding agents to the Moshi mobile app (prebuilt vendor binary)";
    longDescription = ''
      moshi-hook installs hook configuration into supported coding agents,
      serves the local Unix socket those hooks post events to, exposes a
      localhost gateway for the iOS app's diff and browser-preview features,
      and holds a WebSocket to Moshi for approval round-trips and status.
    '';
    downloadPage = "https://getmoshi.app/docs/hooks";
    license = lib.licenses.unfree;
    mainProgram = "moshi-hook";
    maintainers = with lib.maintainers; [ cameronraysmith ];
    platforms = lib.attrNames systemToAsset;
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
  };
})
