{
  # OUTER: Flake-parts module signature
  ...
}:
let
  content =
    {
      # INNER: Home-manager module signature
      config,
      lib,
      pkgs,
      flake, # from extraSpecialArgs
      ...
    }:
    let
      # The age key and every decrypted file live on tmpfs, never in $HOME and so
      # never in the image: the sandbox has no /run/user/<uid>, and /dev/shm is
      # the writable tmpfs it does have. sops-install-secrets writes decrypted
      # files under the mount point and only symlinks them from the paths
      # consumers name, so the symlinks left in $HOME carry no plaintext and do
      # not exist until an install runs.
      sopsDir = "/dev/shm/ubuntu-sops";

      installScript = config.launchd.agents.sops-nix.config.Program;
      sopsEnvironment = lib.concatStringsSep " " (
        lib.mapAttrsToList (name: value: "'${name}=${value}'") config.sops.environment
      );
    in
    {
      home.stateVersion = "23.11";

      # Devin owns ~/.bashrc and ~/.bash_profile and rewrites them at session
      # start, and agent shells are non-interactive, so home-manager's bash
      # configuration is unreachable here and only collides with them.
      programs.bash.enable = lib.mkForce false;

      # `core/bitwarden.nix` starts ssh-agent as a systemd user service on
      # Linux, and the sandbox has no systemd user manager to run it.
      services.ssh-agent.enable = lib.mkForce false;

      # The sandbox image ships only the C.UTF-8 locale, so core's en_US.UTF-8
      # would make every shell warn from hm-session-vars.sh.
      home.sessionVariables = {
        LANG = lib.mkForce "C.UTF-8";
        LC_ALL = lib.mkForce "C.UTF-8";
        LC_CTYPE = lib.mkForce "C.UTF-8";
      };

      # The sandbox runs standalone home-manager with no session bus and no
      # systemd user manager, so sops-nix's user unit never starts and its
      # secrets would never be installed.
      sopsInstallWithoutSystemd.enable = true;

      sops = {
        defaultSopsFile = flake.inputs.self + "/secrets/home-manager/users/ubuntu/secrets.yaml";

        age.keyFile = lib.mkForce "${sopsDir}/age/keys.txt";

        # sops-install-secrets resolves the runtime directory before it inspects
        # any path, and on linux that is $XDG_RUNTIME_DIR with no fallback
        # (pkgs/sops-install-secrets/linux.go:14-20, main.go:1331-1336), so in a
        # sandbox that sets none it fails whatever the paths are. Pointing it at
        # the tmpfs directory both sets it and makes defaultSecretsMountPoint's
        # own default, %r/secrets.d, resolve there, so no path override is needed
        # to keep decrypted files off disk.
        environment.XDG_RUNTIME_DIR = sopsDir;

        secrets = {
          # Git and jujutsu signing read the private key directly on Linux, and
          # `development/radicle.nix` places it at ~/.radicle/keys/radicle.
          ssh-signing-key = {
            mode = "0400";
          };
          linear-api-key-personal = { };
          linear-api-key-work = { };
          linear-workspace-personal = { };
          linear-workspace-work = { };
        };

        templates."linear-credentials.toml" = flake.lib.mkLinearCredentialsTemplate config;
      };

      # The other users render allowed_signers through a sops placeholder
      # because their signing key's public half is itself withheld. This one is
      # already published as a GitHub signing key, so it is written directly and
      # costs no secret. `development/git.nix` points
      # `gpg.ssh.allowedSignersFile` at this path.
      xdg.configFile."git/allowed_signers".text = ''
        ${flake.users.ubuntu.meta.email} namespaces="git" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBTeBMUfte7k9yugPtmVLJONiwxZtyoNotfwBOMAEHGz
      '';

      programs.git.settings = {
        user.name = flake.users.ubuntu.meta.fullname;
        user.email = flake.users.ubuntu.meta.email;
      };

      # Devin sources $ENVRC under `set -a` at the top of every exec shell, and
      # $ENVRC sources this file, so this runs before every tool call. That is the
      # only automatic session-start trigger available: the blueprint's
      # maintenance block is surfaced to the agent rather than executed. The
      # snapshot build activated this profile with no secret, so installing them
      # is what a session still owes, and this is where it happens.
      xdg.configFile."vanixiets/session-env.sh".text = ''
        # Generated by home-manager. Sourced into every exec shell Devin starts,
        # under `set -a`, so it sets no shell options, installs no traps in the
        # caller, changes no directory, never exits, and prints nothing unless
        # something actually went wrong.

        if [ -r /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        fi
        # Absent until home-manager has installed a generation, which is why this
        # is guarded rather than assumed.
        if [ -r "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
          . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
        fi

        __vanixiets_install_sops_secrets() {
          local dir=${sopsDir}
          local stamp=${sopsDir}/session-install.stamp
          local lock=${sopsDir}/session-install.lock
          local log=${sopsDir}/session-install.log
          # shellcheck disable=SC1007  # these are empty initializers
          local status= stamped= now= mtime= rc=0

          # Fast path, taken before any fork: the stamp records the key bytes this
          # hook last acted on and whether that attempt succeeded. Comparing raw
          # bytes rather than a hash keeps this to a stat, a read and a string
          # compare, which matters because this runs before every tool call; it
          # also keeps normalization solely in seed-age-key, so the two cannot
          # disagree about whether a key changed.
          if [ -r "$stamp" ]; then
            { read -r status; IFS= read -r -d "" stamped; } < "$stamp" || true
            if [ "$stamped" = "$SOPS_AGE_KEY" ]; then
              if [ "$status" = ok ]; then
                unset -v status stamped
                return 0
              fi
              # A failure is retried, but at most once a minute, so a broken key
              # or a broken sops file cannot make every tool call pay for an
              # install attempt. EPOCHSECONDS is a bash builtin; date is the
              # fallback and only ever runs on this path.
              now=''${EPOCHSECONDS:-$(${pkgs.coreutils}/bin/date +%s)}
              mtime=$(${pkgs.coreutils}/bin/stat -c %Y "$stamp" 2>/dev/null || echo 0)
              if [ $((now - mtime)) -lt 60 ]; then
                unset -v status stamped now mtime
                return 0
              fi
            fi
          fi
          # `set -a` exports every live variable into a forked child, so the
          # superseded key must not still be in scope when the install runs.
          unset -v status stamped now mtime

          # /dev/shm is world-writable and sticky, so the directory is created
          # rather than adopted, and an existing one is used only when this user
          # owns it and it is not a symlink.
          if [ -L "$dir" ]; then
            printf 'sops: %s is a symlink; refusing to use it\n' "$dir" >&2
            return 1
          elif [ -d "$dir" ]; then
            if [ ! -O "$dir" ]; then
              printf 'sops: %s is not owned by this user; refusing to use it\n' "$dir" >&2
              return 1
            fi
            # An adopted directory is tightened rather than trusted: it may
            # predate this hook at a looser mode, and the age key is about to be
            # written into it. Only reached on the miss path.
            chmod 700 "$dir" 2>/dev/null || true
          elif ! mkdir -m 0700 "$dir" 2>/dev/null; then
            printf 'sops: cannot create %s\n' "$dir" >&2
            return 1
          fi

          # The lock is held by the kernel on fd 9, so it is released when the
          # holder dies however it dies; a mkdir lock would survive a SIGKILL and
          # silently suppress the install for the rest of the session. 97 marks
          # "another shell holds it" so that case leaves the stamp alone.
          (
            ${pkgs.util-linux}/bin/flock -n 9 || exit 97
            ${lib.getExe pkgs.seed-age-key} --key-file ${config.sops.age.keyFile} \
              && env ${sopsEnvironment} ${installScript}
          ) 9> "$lock" > "$log" 2>&1 || rc=$?

          if [ "$rc" -eq 97 ]; then
            return 0
          fi

          if [ "$rc" -eq 0 ]; then
            printf 'ok\n%s' "$SOPS_AGE_KEY" > "$stamp" 2>/dev/null || true
          else
            printf 'failed\n%s' "$SOPS_AGE_KEY" > "$stamp" 2>/dev/null || true
            printf 'sops: secret install failed; see %s\n' "$log" >&2
          fi
          chmod 600 "$stamp" 2>/dev/null || true
        }

        if [ -n "''${SOPS_AGE_KEY:-}" ]; then
          __vanixiets_install_sops_secrets || true
        fi
        unset -f __vanixiets_install_sops_secrets
      '';
    };
in
{
  flake.users.ubuntu.contentPrivate = content;
}
