apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: step-ca-secrets
    namespace: step-ca
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:gm7qNRg/6h+3ieTWGseAD4d8lV7aCa//rWEjnZ4j0HCsr5q1Vg==,iv:e8L/97zL7IYK6JvMkBRr2kkiyzQhj7EB6XrT7e8t/mc=,tag:eMRwwk5ApA92wrwQ+eWRfw==,type:str]
          type: ENC[AES256_GCM,data:mNbiI2B5bgEYCCWttGllxcPt5vUahkksTA==,iv:iCTllh9WyEYD/Bk1+q+HXgqDKGegM1acC8YhgBjAjZk=,tag:mS4W/sGglRJpfUcUWCamjg==,type:str]
          stringData:
            password: ""
        - name: ENC[AES256_GCM,data:8zFysGSga9qSbHQEmfeDOeyR5owVCCEmJfNZ7406UyDP,iv:aMx41iAB9VxQW3UQjuLwmekNl2cijGxd6ihLf2yOfZ4=,tag:/V3NlDdFbZw22zYmniRZTw==,type:str]
          type: ENC[AES256_GCM,data:SonqIC9s51DeX0mnE0k9RrD7XTxwbjMhVLU=,iv:8otszFoKZXX7S+g5nOkN/mHM3JgH5LJzJBHbrynxSl0=,tag:dwpd3uUkRdRiO2oS+Hf1qQ==,type:str]
          stringData:
            root_ca_key: ENC[AES256_GCM,data:El7R9GJrI3CJfoPQwcv3Gx4TnyHdHT4aEQChPIaa0XPHU74l3e5RyfSNs6I9adFR/2w1J+OgpUilo/yNbTTaFgbKwXFkvQL9B/ksQ9GsXLA52F5Ket6XJvtzjDflw90F6UvEIBmgq33Zfpq7QteOm1MVpPbg3RGD00gQ4aJyFwO5YJCHOQMr3tVvtFFTHWnK5woP/LX8t3kZ8zwUwGF/kYo+O4/EZyi5ObYJaKx2nSdm4aOPwodxxW4HWcT3/wWUyyN6jGyJdvUClZp5wiyVbSQBce4cTN7SAOH1i8q7SaXwOi8=,iv:ujhWAZUbJvzybmAEGRInP8qvDLPtnaFmL/EP1zEUXiQ=,tag:vjOlPma8zt5IKDaYKzhmEg==,type:str]
            intermediate_ca_key: ENC[AES256_GCM,data:SCUtejAAEcJdV6YfGmhw8WubtdnSk2fq6eY+3vX0xCdn1UtE6Etf+jLSBRYnkLw0m9eXa2O1y8MEPYkwc/AfC3iYUiVqOnbrnz9Ypkkaf9ufPvCMX7UfkCZrM0vTOujX3DXG2/Z2YJCXJyW/iHglraPtRWEr6DsWitWI+Hw0nNJ/Y4L1ui0E38Rbs2Ob/G8TPRxI3Iwgm8vhaVrrd38h0qLdT7VdtE87V5jPg5gmGYwAUbUiQk5VS5iG/zqRjhjUjkkmR7LyvbDzsyyaPnsvD6DTpkqKWZgRWT/aHBD6E8yS/nY=,iv:IcwXfw4/pCqikbkU+iW+k287htLNm+y6O+tvOwJ1BgY=,tag:oDehU0Fj4d9C5klUpAyzXA==,type:str]
sops:
    age:
        - recipient: age1vy7wsnf8eg5229evq3ywup285jzk9cntsx5hhddjtwsjh0kf4c6s9fmalv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU01kbTcyOVIrQXJhU0tp
            VnkzZkUxbTZxWitvY3BIWlVISkNjT3dVYVdBClQ0TFFLWkJGa3BMSGtpOW1XdWdT
            YWMrZnVzc3N4VGI5OEltZEYxcmFKMmsKLS0tIDRpd2ZYVDNFcTFrOCtZeXI1SDVR
            b01xa0lGYlNPQUcrQWp0QWZaUzdHU1UKgq8ZevH0Ix/ZcNMX0fbjHymhxOOaqHgP
            mTNrKE1mIph70TXuwtYyO8TldOt1lMsLo6pr3pD5B7uFiwAJXFVUIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1js028xag70wpwpp47elpq50mjjv7zn7sxuwuhk8yltkjzqzdvq5qq8w8cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzakNLNU0zTUEwL1FRZlZ6
            Z0l6M1V5UUJ6aXlLOGNMeFUyVmtoREZNWFg0CklvcysvaGFyanpsbDFZa2NKeDRu
            WFZCQ3h5azF0M3E0MjhrS1l3QXptdE0KLS0tIGhRQWcwN294bFcvblJ2RUU5c09Z
            MTUvdHMrMko5dnJNVFVBNStYV2VhUUkKsO6UvZPZ3dmnHbN7M04G1aj+OSZZobkf
            dwJRTLjEZn9tyNoClMvftgrSYOmw8cosi43VGgJmLPkl3kTunJC+2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ldx73kk4kvl3mycjdhngxrrv69wn7cvhreqwzl0gphuftnj5pulqaprgel
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWVgrc3M5Z2lTR1dUODNM
            VU5QemY3RHp0R1lQU3JQczVhOHBnNUYrT2l3CjhLNmNleVZaN3FVVnlINEZwM1lH
            UTBweG03U2F1WXR1L2lJbWlzWFNQZzgKLS0tIDZxSWFRV1ZUejNRWDJtWll5b0pm
            NDBaQTE4eUxqOER2aTZEa3c2M3NVL28KUczagAMY8KXn+fWg9R2XG0P5MSL22/9o
            VWBz/2c8j1ZT/hWooa3xCfyG7DW0pQ5wD2lF13mIp92PX9CyRNV6VQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vn8fpkmkzkjttcuc3prq3jrp7t5fsrdqey74ydu5p88keqmcupvs8jtmv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZFI5aXJpbG9ST01uTGdW
            ajlrSmtFNVdrckN1c0RCZG9BdTZHenJoQ2tvCjRmRWsvbVdaTnBRR3g3K1RWSGRx
            WU5SVXFqRzZoZ3V0QWc5bTBGRjg0cVUKLS0tICs5MWh0K01hTXFFeFdMSzQzbEc5
            ZzBvUXFZZjZoaUZRemkrYXV4aVc4WDAK4+gwlSdDWugV7DLpRgUYzWQwmIFy9tXc
            EH6rkU9RQOgXC1yLbyZ6oKbJ27XJmqQxAvi3nv6IO80jDvzt6svXhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T22:41:20Z"
    mac: ENC[AES256_GCM,data:MxeV+wehbEWUf/a+HO/bxJBXTuYDSJlPR3UmLmVh/jETvt7zzPn7W2s0kcKs9X5koEUwtlKBs9FJseNrOyupIj3jfxCqcJ58cQT+/s3JfwTO8Cykyf5cBjgYLjOHCZ/Tv4ScOGiHm7ZuLI1MF4Ge/QvbDmV0q7O2f6n3bdm1/4Y=,iv:E5whgHW6DwmmmSnZ/5HRT5jDS7wO8qzZ2r0rDc8Ca1I=,tag:u4ziriDRwXJcUaxAR+QCcQ==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
